### ISSUE TITLE
Bug: Spatial field validation fails while we harvest datajson

### ISSUE THREAD

**Issue by avdata99** [GSA/catalog.data.gov#55]
Error at DCAT-US harvest sources while we harvest them ([report here](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e4177f8#gid=1667396946)). 

```
ckan.logic.ValidationError: 
{
  'spatial': [
     u'Error decoding JSON object: Extra data: line 1 column 7 - line 1 column 23 (char 6 - 22)'
  ]
}
```

This issue stems from [#312](https://github.com/GSA/datagov-ckan-multi/issues/312)

## How to reproduce it
 - Add a harvest source
   + Type: data.json
   + URL: http://www.consumerfinance.gov/data.json
 - Try to harvest

This source is harvested in production:
 - [Link to surce](https://catalog.data.gov/harvest/cfpb-json) + [status harvest in API](https://catalog.data.gov/api/3/action/harvest_source_show?name_or_id=cfpb-json)
 - [Sample dataset OK](https://catalog.data.gov/dataset/consumer-complaint-database)

![image](https://user-images.githubusercontent.com/3237309/83640448-855cbb80-a582-11ea-965c-5f6dd0a77db4.png)

## Task
 - [x] Determine what is the source of the problem
 - [x] Send a PR to fix it
 - [x] Create an updated report on the state of the harvesting processes after solving this problem
 - [x] Add a test case for a DCAT-US source with `spatial` field

### Code

This error happens in the spatial extension, [here](https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/plugin.py#L108-L118).  
The GSA fork also includes the same code and should also fail 
The GeoDataGov ext avoid the error by doing a _roll up_ extras before `package_create` [here](https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/plugins.py#L424-L435) so the spatial ext is not able to find the broken _spatial_ extra.

```
if action_name in self.ROLLUP_SAVE_ACTIONS:
    extras_rollup = {}
    new_extras = []
    for extra in data_dict.get('extras', []):
        if extra['key'] in self.EXTRAS_ROLLUP_KEY_IGNORE:
            new_extras.append(extra)
        else:
            extras_rollup[extra['key']] = extra['value']
    if extras_rollup:
        new_extras.append({'key': 'extras_rollup',
                           'value': json.dumps(extras_rollup)})
    data_dict['extras'] = new_extras
```
This feature avoids the `spatial` validation for the _spatial_ extra.

[At GSA CANK 2.3](https://github.com/GSA/ckan/blob/44933abc812675743d0f56641816c36ad25c8325/ckan/logic/__init__.py#L427-L434) we allow to override `before_action` and `after_action` functions to all extensions. This [is not available at CKAN 2.8](https://github.com/ckan/ckan/blob/d1a614a7ec5dd62979b300f1c801dfa7ac9bc410/ckan/logic/__init__.py#L466)

The GeoDataGov extension [uses this](https://github.com/GSA/ckanext-geodatagov/blob/f1ecb14097082a8cd7a1c54807433911ef802af1/ckanext/geodatagov/plugins.py#L407) function to _roll up_ extras. 

**Notes**
 - The ideal fix should be to use some hook before `package_update` and `package_create` but the [class IPackageController](https://github.com/ckan/ckan/blob/master/ckan/plugins/interfaces.py#L598) seems not include a `before_create` or `before_update` hooks.
 - We should add an issue to allow `spatial` as a string or deal with this in a different way. Avoid a validation is not a real fix here.

**Comment by avdata99** [comment]
The source to QA this is added [here](https://catalog-next.sandbox.datagov.us/harvest/ceb84d53-2594-42db-85f6-6808a61d1065) but the process never seems to end (as in [GSA#324](https://github.com/GSA/datagov-ckan-multi/issues/324)). 
This source has two datasets with `spatial: United States`. Is what we need to QA.

**Comment by thejuliekramer** [comment]
I was able to test this in catalog.data.gov using [this](https://www.archives.gov/files/data.json) harvest source  which has a [dataset](https://catalog-next.sandbox.datagov.us/dataset/amending-america-proposed-amendments-to-the-united-states-constitution-1787-to-2014) which includes the spatial field. This harvested the dataset successfully 
<img width="668" alt="Screen Shot 2020-06-18 at 1 23 30 PM" src="https://user-images.githubusercontent.com/7378770/85057887-eed5f000-b166-11ea-85bf-12309c8eebe3.png">
