### ISSUE TITLE
Test Collections from WAF Harvest Source

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/catalog.data.gov#72]
## User Story

As a data.gov developer I want to test that the existing collections being harvested from a WAF harvest source are being harvested correctly

**Acceptance Criteria**
* [ ] When I search for a parent dataset (need live example of collection from WAF harvest source)
* [ ] Then I see it in search results

* [ ] When I search for a child dataset (need live example of collection from WAF harvest source)
* [ ] Then I do not see the child dataset in the search results, but I do see the parent dataset in the results (need live example of collection from WAF harvest source)

* [ ] WHEN I click on a collection 
    * [ ] THEN I can see all datasets that belong to that collection 
    * [ ] AND I can search within a collection for datasets that belong to that collection 

**Task-list** 
* [ ] Find a live example of collection from WAF harvest source
* [ ] Write test for WAF harvest source
* [ ] Tests are green

**Comment by avdata99** [comment]
WAF sources do not use collections. We use waf-collection for this cases which is already covered at #71.
Proposed to close.
