### ISSUE TITLE
Test Collections from CSW Harvest Source

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/catalog.data.gov#73]
## User Story

As a data.gov developer I want to test that the existing collections being harvested from a CSW harvest source are being harvested correctly

**Acceptance Criteria**
* [ ] When I search for a parent dataset (need live example of collection from CSW harvest source)
* [ ] Then I see it in search results

* [ ] When I search for a child dataset (need live example of collection from CSW harvest source)
* [ ] Then I do not see the child dataset in the search results, but I do see the parent dataset in the results (need live example of collection from CSW harvest source)

* [ ] WHEN I click on a collection 
    * [ ] THEN I can see all datasets that belong to that collection 
    * [ ] AND I can search within a collection for datasets that belong to that collection 

**Task-list** 
* [ ] Find a live example of collection from CSW harvest source
* [ ] Write test for CSW harvest source
* [ ] Tests are green
